included:
  - cybexMobile
excluded:
  - cybexMobile/addons
  - cybexMobile/Services/HTTP/Gateway
  - cybexMobile/UI/LGButton
cyclomatic_complexity:
  - 10
  - 30
variable_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1