language: swift
osx_image: xcode10
cache:
  directories:
    - Carthage
    - NBLCommonModule/Carthage
before_install:
  - wget -qO- -O tmp.zip https://drive.google.com/uc\?authuser\=0\&id\=1OrPBwZEamemQbtlRm2hj1Z1xqTJXqMYv\&export\=download && unzip tmp.zip && rm tmp.zip
  - brew install lvillani/tap/carthage-copy-frameworks
  - bundle install
  - bundle update
  - bundle exec pod repo update --silent
  - carthage bootstrap --no-use-binaries --platform iOS --cache-builds
  - cd "./NBLCommonModule/" && carthage bootstrap --no-use-binaries --platform iOS --cache-builds
script:
  - .travis/build.sh
