language: swift
osx_image: xcode10.1
xcode_workspace: cybexMobile.xcworkspace
notifications:
    slack: cybexio:Km9uGhorR7XtYUVoaA8WQ3i6
before_install:
    - mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
    - cp .travis/AdHoc_cybex.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
    - cp .travis/AppStore_cybex.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
    - touch R.generated.swift && chmod 777 R.generated.swift
script:
    - ".travis/build.sh"
env:
    global:
        - secure: Cmdmfc8C7LaPtW0ET4yT0/8Kr6wrTKZtwEXjXDC8E1cTkyzZmIUFaNCT3J4HWujkmYJP+Awvk9Pf7gQGlORyOpVBLCPDepTd1JX17MzIJuuW9MIjgYLLkPmV1IUEMWgisoXi0PxVuqaUgyh58ON5mMHXHMBUXxjIJsaPfL+vhqmI9uo8JAHAYCBCsjJKdhkaGtWJvnfwAL6O2cJ5tF7Sy/0uwZGOCg/HIgoOl4j2SZrJPmQLVllF1mN/3ToAmEOkr/8O5v/C4Y+WWZTrDenwwMMN4yFeNPNKBWsk2JQrjphe7OwhzpbjdzO5AumBnyZ2Nj+kjVdCLbbGSuoDd6uqFrO9SGRf7ScEY2VphLmEjGyjBt8p5C9CS1FEg8Jtpu1lcXiE01Pra+ev0UTYcjtpq8Uc60x7UwQnhxzunNr6q+UowVPqCalim+v1ZfYZlWTBrIAXjSJyqzghliWXL3FTVn9sitplLAyTcbpyZ1PI7bUHYa5wqqaI575RBp1RbOBnRhIzc4QBTZ4hkET3DU/5wbP0pEEuBGGXV1QhD3vxAjb4Miiq3wFuWnmcWNDze6FWkOfC2oMCU2XVQyW2zWYGktvNu3CBKpuAHzYbIypol/GYZ0AJfO7rXhJ996iHki9IEKQhLrJSQtJQkSqZCEWDC/4w9LVTFTfyteqWfFGlDxI=
