language: swift
osx_image: xcode10.0
cache:
  - bundler
before_install:
  - brew install lvillani/tap/carthage-copy-frameworks
  - bundle install
  - bundle update
  - bundle exec pod repo update --silent
  - carthage bootstrap
  - cd "./NBLCommonModule/" && carthage bootstrap
script:
  - fastlane fir
