language: swift
osx_image: xcode10
cache:
  directories:
    - Carthage
    - NBLCommonModule/Carthage
before_install:
  - brew install lvillani/tap/carthage-copy-frameworks
  - bundle install
  - bundle update
  - bundle exec pod repo update --silent
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds
  - cd "./NBLCommonModule/" && carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds
script:
  - fastlane fir
